application: flash-cards
version: 1
runtime: python
api_version: 1

handlers:
- url: /.*
  script: flash-cards.py
  
- url: /js
  static_dir: js
  
- url: /images
  static_dir: images
  
- url: /style
  static_dir: style